spring.datasource.url=jdbc:postgresql://localhost:5432/dbclinic
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.open-in-view=false

spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true

spring.mvc.static-path-pattern=/static/**
spring.web.resources.static-locations=classpath:/static/

springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.tryItOutEnabled=true